### ISSUE TITLE
misdetection ?

### ISSUE THREAD

**Issue by joejoe2** [murphysec/murphysec#5]
請問這位是你們平台的嗎 ? 他說我用的h2版本有問題
https://github.com/joejoe2/spring-jwt-template/issues/1#issue-1144759740

不過實際上我用的是1.4.200
![image](https://user-images.githubusercontent.com/39475537/154808778-0cfbc77d-c3d3-4288-aa37-51b3cfde21ae.png)

postgresql也偵測錯誤
![image](https://user-images.githubusercontent.com/39475537/154809252-8a454887-4d6c-4427-92b8-0133a068d945.png)

**Comment by cpdyj** [comment]
目前这块我们正在完善，后续应该会更准确一点。
