### ISSUE TITLE
Why are github bots for this repo opening unsolicited security issues in my projects?

### ISSUE THREAD

**Issue by Xetera** [murphysec/murphysec#6]
Not sure if this repo is associated with the codescans but I had a bot open a public issue for a security vulnerability in one of my repos

- https://github.com/Xetera/wordle-search/issues/1

https://github.com/Abbykawai
https://github.com/abbymiss

Not a big deal since isn't an important repo for me, but I never opted into these code scans. Publicly disclosing vulnerabilities in repos that might have a special vulnerability disclosure process is a really bad idea. I imagine these bots are breaking Github's ToS too since this is unwanted automated interaction similar to spam.

**Comment by cxxxzy** [comment]
Got it. We'll investigate this case.

**Comment by magodo** [comment]
@cxxxzy The issue still remains: https://github.com/magodo/ged/issues/2. Please reopen this issue until it got resolved.

**Comment by Xetera** [comment]
Looks like their bots are being banned and they're just creating new accounts. If that's not abuse I don't know what is lol

**Comment by cxxxzy** [comment]
I noticed that the vulnerabilities mentioned in these issues are all officially disclosed publicly. The original intention of the issue I think should be to help developers improve the security quality of their code. Sorry for any inconvenience caused. As far as I know, this reminder will never be more than once, don't worry about being bothered again. If you think the reminder content is useless, please ignore or delete it directly.

**Comment by Xetera** [comment]
I know you have good intentions and I think this is a cool project too. But I'm sure as you can also tell by your previous accounts being deleted, Github probably doesn't want these kinds of bots on their platform because this is unchecked, automated behavior users did not consent to receiving (unless they were deleted on purpose I guess).

Not to mention, if the scan is only done for one vulnerability a single time, it's not exactly a useful code scanning tool as much as it is a nuisance. I don't think what you're doing is bad, but there are better way to approach this to make it a useful tool and not a confusing one-time surprise that developers have to track down to get more context on.
